name: ServerManager
version: '$version'
main: dev.wh2sperx.ServerManager
api-version: '1.21'
load: STARTUP
authors: [ wh2sperx ]
website: https://qhuyy.tech
depend: [ AuthMe ]
softdepend: [ PlaceholderAPI, Vault ]

commands:
  admin:
    description: ServerManager admin commands
    permission: wh2sperx.admin
    permission-message: "You don't have permission to use this command."
    usage: /<command> <list|grant|revoke|login|reload>

permissions:
  wh2sperx.admin:
    description: Access to all ServerManager admin commands
    default: op
