name: ServerManager
version: '$version'
main: dev.wh2sperx.ServerManager
api-version: '1.21'
load: STARTUP
authors: [ wh2sperx ]
website: https://qhuyy.tech
depend: [ AuthMe, ProtocolLib ]
softdepend: [ PlaceholderAPI, Vault ]
libraries:
  - org.mindrot:jbcrypt:0.4
  - com.h2database:h2:2.4.240
  - com.github.cryptomorin:XSeries:13.6.0

commands:
  admin:
    description: ServerManager admin commands
    permission: wh2sperx.admin
    permission-message: "You don't have permission to use this command."
    usage: /<command> <list|grant|revoke|login|reload>

permissions:
  wh2sperx.admin:
    description: Access to all ServerManager admin commands
    default: op
